// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_date_amount_interest_ from "./routes/partials/[date_amount_interest].tsx";
import * as $Button from "./islands/Button.tsx";
import * as $InterestInputs from "./islands/InterestInputs.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/partials/[date_amount_interest].tsx":
      $partials_date_amount_interest_,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/InterestInputs.tsx": $InterestInputs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
